name: test
on: [ push, pull_request ]
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
        - 24.3
        - 24.4
        - 24.5
        - 25.1
        - 25.2
        - 25.3
        - 26.1
        - 26.2
        - 26.3
        - 27.1
        - 27.2
        - 28.1
        - 28.2
        - snapshot

    steps:
    - name: Checkout url-scgi
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Build url-scgi
      run: make all

    - name: Test url-scgi
      run: make test
